<?php

namespace Blog\ModelBundle\Repository;

use Blog\ModelBundle\Entity\Author;
use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    /**
     * @return Author
     */
    public function findFirstAuthor()
    {
        return $this->_em->getRepository('ModelBundle:Author')
            ->createQueryBuilder('a')
            ->setMaxResults(1)
            ->orderBy('a.id')
            ->getQuery()
            ->getSingleResult();
    }
}
