<?php

namespace Blog\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

    public function findTagsWithPost()
    {
        $query = $this->_em->getRepository('ModelBundle:Tag')
            ->createQueryBuilder('t')
            ->distinct()
            ->where('t.posts is not empty')
            ->getQuery();

        return $query
            ->getResult();

    }

}
